"""add max_registrants to camp_sessions

Revision ID: 26ccc607fff9
Revises: 7bfd5239a1a4
Create Date: 2026-04-13 16:18:21.990171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ccc607fff9'
down_revision = '7bfd5239a1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_registrants', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_sessions', schema=None) as batch_op:
        batch_op.drop_column('max_registrants')

    # ### end Alembic commands ###
