"""add indexes to hot columns

Revision ID: 332621fd528d
Revises: 26ccc607fff9
Create Date: 2026-04-19 08:57:58.373208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332621fd528d'
down_revision = '26ccc607fff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_logs', schema=None) as batch_op:
        batch_op.create_index('ix_checkinlog_session_day_type', ['camp_session_id', 'camp_day', 'event_type', 'voided'], unique=False)
        batch_op.create_index('ix_checkinlog_staff_day', ['staff_user_id', 'camp_session_id', 'camp_day', 'voided'], unique=False)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_parent_user_id'), ['parent_user_id'], unique=False)

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_status'))

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_parent_user_id'))

    with op.batch_alter_table('checkin_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_checkinlog_staff_day')
        batch_op.drop_index('ix_checkinlog_session_day_type')

    # ### end Alembic commands ###
