"""add independent_travel_default to child

Revision ID: 7bfd5239a1a4
Revises: a4a8a9f69c6f
Create Date: 2026-03-24 12:01:25.355577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfd5239a1a4'
down_revision = 'a4a8a9f69c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('independent_travel_default', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_column('independent_travel_default')

    # ### end Alembic commands ###
