"""initial schema

Revision ID: a4a8a9f69c6f
Revises: 
Create Date: 2026-03-13 20:25:34.057267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a8a9f69c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('device_type', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camp_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('registration_open', sa.Boolean(), nullable=False),
    sa.Column('registration_opens_at', sa.DateTime(), nullable=True),
    sa.Column('registration_closes_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('require_head_coaches', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_versions',
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=30), nullable=False),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_postcode', sa.String(length=20), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verify_token', sa.String(length=255), nullable=True),
    sa.Column('verify_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invite_token', sa.String(length=255), nullable=True),
    sa.Column('invite_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('manually_entered', sa.Boolean(), nullable=False),
    sa.Column('manually_entered_by', sa.Integer(), nullable=True),
    sa.Column('manually_entered_at', sa.DateTime(), nullable=True),
    sa.Column('email_announcements', sa.Boolean(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('last_active_year', sa.Integer(), nullable=True),
    sa.Column('retention_flag_date', sa.Date(), nullable=True),
    sa.Column('deletion_warning_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manually_entered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('age_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_session_id'], ['camp_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_session_id', 'name')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('camp_session_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('target_age_groups', sa.String(length=100), nullable=True),
    sa.Column('staff_tags', sa.String(length=100), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('photo_s3_key', sa.String(length=255), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['camp_session_id'], ['camp_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=True),
    sa.Column('reporter_email', sa.String(length=255), nullable=False),
    sa.Column('reporter_role', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('photo_consent_default', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('sendgrid_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_class', sa.String(length=20), nullable=False),
    sa.Column('is_first_aid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('phone_primary', sa.String(length=30), nullable=False),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_session_id', sa.Integer(), nullable=False),
    sa.Column('age_group_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('is_head_coach', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camp_session_id'], ['camp_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_session_id', 'age_group_id', 'staff_user_id')
    )
    op.create_table('qr_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('regenerated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('camp_session_id', sa.Integer(), nullable=False),
    sa.Column('age_group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('auto_assigned_group', sa.String(length=20), nullable=True),
    sa.Column('admin_override', sa.Boolean(), nullable=False),
    sa.Column('admin_override_reason', sa.Text(), nullable=True),
    sa.Column('admin_override_by', sa.Integer(), nullable=True),
    sa.Column('admin_override_at', sa.DateTime(), nullable=True),
    sa.Column('independent_travel', sa.Boolean(), nullable=False),
    sa.Column('independent_travel_approved_by', sa.Integer(), nullable=True),
    sa.Column('independent_travel_approved_at', sa.DateTime(), nullable=True),
    sa.Column('photo_consent', sa.Boolean(), nullable=False),
    sa.Column('paper_consent_data_processing', sa.Boolean(), nullable=False),
    sa.Column('paper_consent_photo', sa.Boolean(), nullable=False),
    sa.Column('paper_consent_independent_travel', sa.Boolean(), nullable=False),
    sa.Column('entered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('consent_version_at_registration', sa.String(length=20), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_override_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camp_session_id'], ['camp_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['independent_travel_approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'camp_session_id')
    )
    op.create_table('absence_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('camp_day', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'camp_day', name='uq_absence_registration_day')
    )
    op.create_table('checkin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('staff_user_id', sa.Integer(), nullable=True),
    sa.Column('camp_session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('camp_day', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('is_auto_checkout', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camp_session_id'], ['camp_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin_logs')
    op.drop_table('absence_reports')
    op.drop_table('registrations')
    op.drop_table('qr_tokens')
    op.drop_table('group_assignments')
    op.drop_table('emergency_contacts')
    op.drop_table('staff_profiles')
    op.drop_table('email_log')
    op.drop_table('children')
    op.drop_table('bug_reports')
    op.drop_table('announcements')
    op.drop_table('age_groups')
    op.drop_table('users')
    op.drop_table('error_log')
    op.drop_table('consent_versions')
    op.drop_table('camp_sessions')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
