"""add camp age limits

Revision ID: c5276cf556a5
Revises: 332621fd528d
Create Date: 2026-04-25 07:42:45.190677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5276cf556a5'
down_revision = '332621fd528d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_age_limit', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('max_age_limit', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('checkin_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkinlog_session_day_type'))
        batch_op.drop_index(batch_op.f('ix_checkinlog_staff_day'))

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_parent_user_id'))

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_status'), ['status'], unique=False)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_parent_user_id'), ['parent_user_id'], unique=False)

    with op.batch_alter_table('checkin_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkinlog_staff_day'), ['staff_user_id', 'camp_session_id', 'camp_day', 'voided'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkinlog_session_day_type'), ['camp_session_id', 'camp_day', 'event_type', 'voided'], unique=False)

    with op.batch_alter_table('camp_sessions', schema=None) as batch_op:
        batch_op.drop_column('max_age_limit')
        batch_op.drop_column('min_age_limit')

    # ### end Alembic commands ###
